language: ruby # default
os: osx
osx_image: xcode8.2

before_install:
  - brew update
  - curl -s https://static.rust-lang.org/rustup.sh | sh -s
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - brew install dmd io planck python3

script: ./test.sh
